name: Dan Henrie
favicon: null
layout_spectrum: 0.68616
typography_spectrum: 0.24766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73233510-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5b5b5d'
    - '#afd25a'
    - '#00aee0'
    - '#d7316f'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
