typography_spectrum: 0.19562
color:
  brandColors:
    - '#199ad9'
    - '#000000'
    - '#0000ff'
    - '#0055aa'
    - '#00ffff'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-73233510-1
  facebook: null
  twitter: null
name: Dan Henrie
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 8378d070-9fa3-4dfa-9328-c4b0af978ec0
    type: content
favicon: null
title: Dan Henrie
purpose: []
