name: Dan Henrie
favicon: null
layout_spectrum: 0.895
typography_spectrum: 0.3476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#079bd9'
    - '#033a51'
    - '#011d28'
    - '#046892'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
