name: Dan Henrie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19562
title: Dan Henrie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73233510-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#199ad9'
    - '#000000'
    - '#0000ff'
    - '#0055aa'
    - '#00ffff'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
