name: Dan Henrie
favicon: null
layout_spectrum: 0.6919
typography_spectrum: 0.32922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfcadc'
    - '#494e54'
    - '#1b212d'
    - '#979aa3'
    - '#f7f7f5'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
