name: Dan Henrie
favicon: null
layout_spectrum: 0.91029
typography_spectrum: 0.99898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfcadc'
    - '#494e54'
    - '#1b212d'
    - '#979aa3'
    - '#f7f7f5'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
