name: Dan Henrie
favicon: null
layout_spectrum: 0.2298293998464942
typography_spectrum: 0.7491810470819473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#079bd9'
    - '#033a51'
    - '#011d28'
    - '#046892'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
