name: Dan Henrie
favicon: null
layout_spectrum: 0.895
typography_spectrum: 0.3476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a06'
    - '#e7cf6f'
    - '#fef8e0'
    - '#6f5b1c'
    - '#9cca2c'
  brandStrength: 0
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
