name: Dan Henrie
favicon: null
layout_spectrum: 0.82337
typography_spectrum: 0.67406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73233510-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5b5b5d'
    - '#afd25a'
    - '#00aee0'
    - '#d7316f'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
