name: Dan Henrie
favicon: null
layout_spectrum: 0.58461
typography_spectrum: 0.24766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53116344-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1cadeb'
    - '#868d96'
    - '#28222f'
    - '#cccbc6'
    - '#1d6f9d'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
